# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d217574d5f0481f6bf9fa81033ad77957d6bf463146b6d17febfade8634c7cbb2429c48e811b9011152025febcbf9e09b92f5e27ce7d528a4c0ed938bf48f346

test:
  secret_key_base: 64db4b72ead4296ce7da5ac67d760e0023ee7ab53df4fdcf6141810f97fd59a176e687e7a64f8d77a8c6d50bf56a3d830765cce1b9dba04f2cb3338e586ca6bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
